name: Python Trigger

on:
  workflow_dispatch:
  push:
    paths:
    - 'test_config.yml'

jobs:
  build-linux:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    
    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
        
    - name: Install python packages
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        
    - name: execute python script
      env:
        SECRET: ${{ secrets.TEST1 }}
        TOKEN: ${{ secrets.PERM_TOKEN }}
      run: python test.py
      
